Repository AY2122S2-CS2103-W16-4/tp, pull requests merged in 2022-03, with the labels that each got.

#45 Add property feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/Region.java
  src/main/java/seedu/address/model/property/Size.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#47 Add favourite feature
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/hsiaojietng.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Favourite.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/FavouriteWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/FavouriteWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#51 Add match feature
  src/main/java/seedu/address/commons/core/Pair.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/DoublePersonCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MatchWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DoublePersonCard.fxml
  src/main/resources/view/MatchWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Story, priority.Medium

#50 Support multiple properties
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/Size.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/DoublePersonCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/property/PriceTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/model/property/RegionTest.java
  src/test/java/seedu/address/model/property/SizeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/PropertyBuilder.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Enhancement, priority.High

#55 Fix sizing of DoublePersonCard
  src/main/java/seedu/address/ui/DoublePersonCard.java
  src/main/resources/view/DoublePersonCard.fxml
Labels: type.Enhancement

#70 Add text warping for table cells and minor GUI adjustments
  src/main/java/seedu/address/ui/formats/HelpTable.java
  src/main/resources/view/HelpTable.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement, severity.VeryLow

#71 Update user and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/developer-guide/UiArchitecture.png
  docs/images/user-guide/helpWindowUi.png
Labels: documentation

#81 Add tests and documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/cindyangxq.md
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: documentation

#91 Add favourite window feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Favouritestar.png
  docs/team/cindyangxq.md
  docs/team/hsiaojietng.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/FavouritesWindowCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Favourite.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/FavouriteWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/FavouriteWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
Labels: enhancement, severity.High

#93 Fix accidental deletion of buyer/seller labels and exit command's beh…
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
Labels: bug, priority.High

#98 Add Documentation and enable assertions
  build.gradle
  docs/DeveloperGuide.md
  docs/xml/UiArchitecture.xml
Labels: documentation

#100 Update documentation & User Guide
  docs/DeveloperGuide.md
  docs/team/waffledood.md
Labels: documentation

#94 Add statistics feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/hsiaojietng.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/FavouritesWindowCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/commands/StatisticsWindowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/commands/StatisticsWindowCommandTest.java
Labels: type.Story, priority.High

#101 Update developer guide with proposed sorting feature
  docs/DeveloperGuide.md
Labels: documentation

#97 Enhance Find feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/cindyangxq.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Preference.java
  src/main/java/seedu/address/model/predicates/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/predicates/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/predicates/PreferenceContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/predicates/PropertiesContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/predicates/UserTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/Property.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/predicates/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/PreferenceContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/PropertiesContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/predicates/UserTypeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, severity.High

#104 Fix issue with closing Main window
  docs/DeveloperGuide.md
  docs/team/waffledood.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/resources/view/StatisticsWindow.fxml
Labels: bug

#95 Add uploading of image and viewimagewindow
  docs/UserGuide.md
  docs/images/user-guide/Upload_Directory_Example.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FavouritesWindowCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/commands/StatisticsWindowCommand.java
  src/main/java/seedu/address/logic/commands/UploadCommand.java
  src/main/java/seedu/address/logic/commands/ViewImageCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UploadCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewImageCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/userimage/FilePath.java
  src/main/java/seedu/address/model/userimage/UserImage.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedUserImage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewImageWindow.java
  src/main/java/seedu/address/ui/formats/HelpText.java
  src/main/resources/images/Missing.png
  src/main/resources/view/ViewImageWindow.css
  src/main/resources/view/ViewImageWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/commands/StatisticsWindowCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UploadCommandParserTest.java
  src/test/java/seedu/address/model/userimage/FilePathTest.java
  src/test/java/seedu/address/model/userimage/UserImageTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/resources/images/fail.png
  src/test/resources/images/notAImage.png
  src/test/resources/images/success.png
  src/test/resources/images/text.txt
Labels: type.Story, severity.High

#67 Add sort feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UploadCommand.java
  src/main/java/seedu/address/logic/commands/ViewImageCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PersonComparator.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Story

#108 Update UI of MatchWindow
  src/main/java/seedu/address/ui/DoublePersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DoublePersonCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, severity.Low

#110 Add keyboard shortcuts and documentation
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewImageWindow.java
  src/main/java/seedu/address/ui/formats/HelpTable.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: documentation, type.Enhancement
