Repository AY2122S2-CS2103-W16-4/tp, pull requests merged in 2022-04, with the labels that each got.

#179 Shift placement of Reminder label
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement, severity.Low

#180 Fix minor documentation bugs
  docs/UserGuide.md
  docs/images/user-guide/addBetsyCroweResult.png
  docs/images/user-guide/addJohnDoeResult.png
  src/main/java/seedu/address/ui/formats/HelpTable.java
Labels: documentation, documentation bug

#178 Specify more implementation of statistics in the future in DG/UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/developer-guide/Stats.png
  docs/images/user-guide/Stats.png
Labels: documentation

#177 Fix favourite behaviour
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/ui/SingleColumnPersonListWindow.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
Labels: bug, severity.High

#182 Bug fixes to `Remind` feature
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/ReminderPersons.java
  src/main/java/seedu/address/ui/ReminderWindow.java
Labels: type.Bug, severity.Medium

#183 Bug fixes (2) & Enhancements to `Remind` feature
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/storage/ReminderPersons.java
Labels: type.Bug

#184 Provide more detailed success message when opening Statistics window
  src/main/java/seedu/address/logic/commands/StatisticsWindowCommand.java
Labels: type.Bug

#186 Add TOC for user guide and readability improvements
  docs/UserGuide.md
Labels: documentation, documentation bug

#187 Add more sorting documentation for UG
  docs/UserGuide.md
  docs/images/user-guide/sortNumPropertiesResult.png
  docs/images/user-guide/sortReverseUserTypeNumPropertiesResult.png
Labels: documentation

#188 Fix string display of person before and after being favourited
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: bug

#197 Add constraint to Preference
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, severity.Medium

#198 Update documentation & unit tests for Remind feature
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/user-guide/reminderWindowEmpty.png
  docs/images/user-guide/reminderWindowFilled.png
  docs/images/user-guide/successfulRemindCommand.png
  docs/team/waffledood.md
  src/main/java/seedu/address/storage/ReminderPersons.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/commands/ReminderWindowCommandTest.java
  src/test/java/seedu/address/model/ReminderTest.java
  src/test/java/seedu/address/storage/ReminderPersonsTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation

#191 Update find and match in UserGuide
  docs/UserGuide.md
Labels: severity.Medium, documentation bug

#190 Update guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Favouritestar.png
  docs/images/developer-guide/RealEstateProModel.png
  docs/images/developer-guide/RealEstateProStorage.png
  docs/images/user-guide/addBetsyCroweResult.png
  docs/images/user-guide/favouritingBerniceYu.png
  docs/images/user-guide/findRobinJohan.png
  docs/images/user-guide/findSamElonResult.png
  docs/images/user-guide/openFavouriteWindow.png
  docs/team/hsiaojietng.md
  docs/xml/RealEstateProModel.xml
  docs/xml/RealEstateProStorage.xml
Labels: documentation

#202 Update UserGuide & DeveloperGuide for Remind feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/ReminderPersonsTest.java
Labels: documentation

#203 Update User and developer guide
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/UserGuide.md
  docs/images/user-guide/helpWindowUi.png
  docs/images/user-guide/viewImageWindow.png
  docs/team/howardwhw2.md
  src/main/java/seedu/address/ui/formats/HelpTable.java
Labels: documentation

#205 Update behaviour of edit command in UG
  docs/UserGuide.md
Labels: documentation

#207 Include process of unfavouriting client
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#204 Update documentation
  docs/DeveloperGuide.md
  docs/team/cindyangxq.md
Labels: documentation

#206 Update DG
  docs/DeveloperGuide.md
  docs/team/ashuh.md
Labels: documentation

#208 Add use cases for `Favourite`, Favourites window and Statistics window
  docs/DeveloperGuide.md
Labels: documentation

#209 Update AboutUs, Developer Guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/developer-guide/RealEstateProStorage.png
  docs/team/cindyangxq.md
  docs/team/howardwhw2.md
  docs/xml/RealEstateProStorage.xml
Labels: documentation
